# Generated by Django 4.2.7 on 2024-05-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "clientapp",
            "0002_rename_status_client_country_remove_client_district_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="placevisited",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placename",
                    models.CharField(
                        blank=True, default=True, max_length=50, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=True, max_length=100, null=True
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
