# Generated by Django 4.2.7 on 2024-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0005_hashtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="age",
        ),
        migrations.AddField(
            model_name="client",
            name="dob",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
