# Generated by Django 4.2.7 on 2024-05-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0006_remove_client_age_client_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placevisited",
            name="description",
        ),
    ]
