# Generated by Django 4.2.7 on 2024-05-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0008_groupinvitation_connections_assignedgroups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="groupid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientapp.wandergroup",
            ),
        ),
    ]
