# Generated by Django 4.2.7 on 2024-05-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0012_commentpost_likepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedgroups",
            name="groupaddmode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="assignedgroups",
            name="is_invited",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="assignedgroups",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
