# Generated by Django 5.0.6 on 2024-06-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0013_assignedgroups_groupaddmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedgroups',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
